### ISSUE TITLE
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

### ISSUE THREAD

**Issue by WXY-Belief** [StoryMY/take-off-eyeglasses#1]
你好，我想问一下，为什么会出现这个问题呀?
Hello, I'd like to ask, why is this problem?

Traceback (most recent call last):
  File "easy_use.py", line 97, in <module>
    generate_results(args, device)
  File "easy_use.py", line 66, in generate_results
    img = transform(img)
  File "/disk/sdb/public_user/anaconda3/envs/wxy_env/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 67, in __call__
    img = t(img)
  File "/disk/sdb/public_user/anaconda3/envs/wxy_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/disk/sdb/public_user/anaconda3/envs/wxy_env/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 226, in forward
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/disk/sdb/public_user/anaconda3/envs/wxy_env/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 284, in normalize
    tensor.sub_(mean).div_(std)
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

**Comment by StoryMY** [comment]
It seems that the channel of img is 4 (RGBA), which is expected to be 3 (RGB). 
You can print(np.array(img).shape) before "img = transform(img)" to check it. 
The correct shape is expected to be (256, 256, 3).

If your result is (256, 256, 4), you need to convert it to RGB first.
Maybe like this: "img = Image.open(os.path.join(args.input_dir, img_name)).convert('RGB')" (Line 64)

**Comment by WXY-Belief** [comment]
Well, thank you very much.I found a solution on Baidu.But now there is another problem. All my documents are shown in the attachment. The program ran for a long time without results. I don't know if this is normal.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StoryMY/take-off-eyeglasses"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 下午5:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StoryMY/take-off-eyeglasses] RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0 (Issue #1)





 
It seems that the channel of img is 4 (RGBA), which is expected to be 3 (RGB).
 You can print(img.shape) before "img = transform(img)" to check it.
 The correct shape is expected to be torch.Size([3, 256, 256]).
 
If your result is torch.Size([4, 256, 256]), you need to convert it to RGB first.
 Maybe like this: "img = Image.open(os.path.join(args.input_dir, img_name)).convert('RGB')" (Line 64)

**Comment by WXY-Belief** [comment]
Sorry, there is something wrong with my configuration environment


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "StoryMY/take-off-eyeglasses"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 下午5:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StoryMY/take-off-eyeglasses] RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0 (Issue #1)





 
It seems that the channel of img is 4 (RGBA), which is expected to be 3 (RGB).
 You can print(img.shape) before "img = transform(img)" to check it.
 The correct shape is expected to be torch.Size([3, 256, 256]).
 
If your result is torch.Size([4, 256, 256]), you need to convert it to RGB first.
 Maybe like this: "img = Image.open(os.path.join(args.input_dir, img_name)).convert('RGB')" (Line 64)
