### ISSUE TITLE
  About input picture size

### ISSUE THREAD

**Issue by WXY-Belief** [StoryMY/take-off-eyeglasses#2]
line54：transforms.Resize(args.img_size)

This line of code will scaling the picture to 256 * 256.However, if I input a 296 * 294 picture, the following error will appear
"RuntimeError: Sizes of tensors must match except in dimension 2. Got 296 and 294 (The offending index is 0)"

after I manually scaled the picture to 256 * 256, the program can run correctly and output the results.

**Comment by StoryMY** [comment]
Well, the code assumed that the "height:width" is "1:1". I have updated related preprocess in the new commit 86c6a95
