### ISSUE TITLE
A question about Synthetic data and Real data

### ISSUE THREAD

**Issue by Wang-Wenqing** [StoryMY/take-off-eyeglasses#3]
Thanks for your excellent work. I have a little question. Whether the real data CelebA (with eyeglasses) is used only for domain adaptation to uniform real domain and synthetic domain? Or it is used in training, for example, mixup real image and synthetic image for training, or fine tune with real image, I have not find this question in the paper, so sorry to bother you.

**Comment by StoryMY** [comment]
The CelebA dataset is used only for domain adaptation (Mask Prediction Stage). In the Item Removal Stage, we only use synthetic data to train De-Shadow/Glass Network.

**Comment by Wang-Wenqing** [comment]
Thanks for your answer~~
